logging:
  level: INFO
  loggers:
    mack.lp3.ws: DEBUG
server:
  rootPath: /api/*
#  applicationConnectors:
#  - type: http
#    port: 9000
#  adminConnectors:
#  - type: http
#    port: 9001
dateFormat: yyyy-MM-dd


